"""Initial migration

Revision ID: 5961483414cf
Revises: 
Create Date: 2026-07-25 18:20:13.080159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5961483414cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('hash_password', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cogs', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('acquiring', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('target_actions', sa.Integer(), nullable=False),
    sa.Column('buyers', sa.Integer(), nullable=False),
    sa.Column('ad_costs', sa.Float(), nullable=False),
    sa.Column('inbound_logistic', sa.Float(), nullable=False),
    sa.Column('direct_logistic', sa.Float(), nullable=False),
    sa.Column('reverse_logistic', sa.Float(), nullable=False),
    sa.Column('return_rate', sa.Float(), nullable=False),
    sa.Column('defect_rate', sa.Float(), nullable=False),
    sa.Column('avg_storage', sa.Float(), nullable=False),
    sa.Column('avg_packaging', sa.Float(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('conversion', sa.Float(), nullable=False),
    sa.Column('cac', sa.Float(), nullable=False),
    sa.Column('required_cpa', sa.Float(), nullable=False),
    sa.Column('ltc', sa.Float(), nullable=False),
    sa.Column('cm', sa.Float(), nullable=False),
    sa.Column('ltv', sa.Float(), nullable=False),
    sa.Column('product_roi', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('products')
    op.drop_table('stores')
    op.drop_table('users')
    # ### end Alembic commands ###
